### ISSUE TITLE
iTunes Visibility Doesn't seems to work?

### ISSUE THREAD

**Issue by terenzeyuen** [facundoolano/aso#11]
Thanks for the library, I have tried the following:
itunes.visibility(284882215).then(console.log);

But getting:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'split' of undefined

**Comment by terenzeyuen** [comment]
Other methods like suggest, etc seems working fine.

**Comment by facundoolano** [comment]
Thanks for reporting, I'll review when I get some time (help is welcome!)

**Comment by facundoolano** [comment]
This is most likely failing because the rss feeds for the itunes scraper `list` method changed (I'm reviewing this issue in app-store-scraper at the moment, it may take a while before a solution gets here).

**Comment by facundoolano** [comment]
fixed now
