### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by vishaletm** [facundoolano/aso#13]
TypeError: Cannot read property 'split' of undefined
I am getting this error while making request for aso.visibility and aso.app

Error stack trace
Node\aso\node_modules\google-play-scraper\lib\app.js:49:64)\
![image](https://user-images.githubusercontent.com/5175910/38781444-65a15fe4-4102-11e8-89b6-7d9fa92ef11c.png)

**Comment by facundoolano** [comment]
This is because ASO uses an old version of google-play-scraper. Updating to the latest version should fix it, but this also requires going through all the recent API changes in the scraper and making sure the ASO code is updated for them.

**Comment by facundoolano** [comment]
@vishaletm If you want to try it the fix would be updating to the latest gplay scraper version, and going through each of the ASO methods to see if something breaks. Some stuff will most likely break, at this point you'd have to debug the ASO code, possibly checking the gplay commit history to see what has been changing lately.

It's not trivial work, but I currently don't have much time to do it myself.

**Comment by igorbest89** [comment]
@facundoolano also I have problem whith aso can you help plz

**Comment by vishaletm** [comment]
@facundoolano I tried to change the version of scrapper. Seems working. Could you please look into my [Pull Request](https://github.com/facundoolano/aso/pull/18)?

**Comment by TheBlackList95** [comment]
I will verify your code for now but i dont know what hapen, what is the
principe of getting ketting keywords from google play ? because your google
play scrapper works really fine, you are good, but aso package not working
i cant see why

Le jeu. 18 oct. 2018 à 08:52, Vishal K M <notifications@github.com> a
écrit :

**Comment by vishal-km** [comment]
Done a test for suggest only

```
aso.suggest({
   strategy: aso.SIMILAR,
   appId: 'com.ubercab.uberlite',
   num: 5}).then(function(result) {
  
   console.log("Initialized user details");
   // Use user details from here
   console.log(result);
}, function(err) {
   console.log(err);
});
```
**Result obtained** _['app', 'taxi', 'https', 'time', 'driver' ]_

**Comment by TheBlackList95** [comment]
Cooool, you are genius bro don't give up, im here with you, we have to make
it running again

**Comment by facundoolano** [comment]
should be fixed now.

**Comment by TheBlackList95** [comment]
Really ? Fixed now ? Everything is good ?

**Comment by facundoolano** [comment]
Just plublished a new version. If you still see an error, please open a new issue.

**Comment by TheBlackList95** [comment]
Good. Proud of you genious. I'll make a unit test to each function then
i'll report if any of them not working correctly
