### ISSUE TITLE
Google Plasy Scrape Not Work check competitors

### ISSUE THREAD

**Issue by mandalaku** [facundoolano/aso#24]
(node:14652) UnhandledPromiseRejectionWarning: Error: App not found (404)
    at C:\Users\user\Desktop\aso-master_2\node_modules\google-play-scraper\lib\utils\request.js:42:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by facundoolano** [comment]
Please include the version of the library you are using and a snippet of code to reproduce the error.

**Comment by mandalaku** [comment]
i tes this

const aso = require('aso')('gplay');

aso.scores('blast').then(console.log)

**Comment by mandalaku** [comment]
latest version

**Comment by facundoolano** [comment]
This was caused by https://github.com/facundoolano/google-play-scraper/issues/280

Updating `npm update google-play-scraper` should do the tricking. Publishing an updated version of aso now.

**Comment by van7hu** [comment]
I have the same problem, any updates ?
