### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by rylax** [facundoolano/aso#38]
Hello,

given the last few posted issues and no response from the creator, I am curious if they project is still being maintained? It would be very sad to see it go. As of now, it seems that something with scraping is broken. I always get a 503 return. I am especially curious since the [app-store-scraper](https://github.com/facundoolano/app-store-scraper) library works perfectly fine.

Thanks!

**Comment by facundoolano** [comment]
I keep an eye on the issues but I don't have plans on adding development hours. I'm always open for reviewing and assisting with pull requests, though.

**Comment by rylax** [comment]
Thanks for the super fast response! Totally understand. Already super cool the time you put into it. I tried looking into the issue, unfortunately without success. So I am hoping for someone else to step in since it's unfortunately practically broken right now.
