### ISSUE TITLE
Process Killed

### ISSUE THREAD

**Issue by gautamm20** [facundoolano/aso#8]
Hello,

I am using the base "google-play-scraper" library very successfully. However, any function in the aso library results in a "Killed" status. No matter what the input or call is.

Just to add, have tested this on three ubuntu VMs with varied RAM configs of 2 GB, 4 GB and 6 GB, all with the same result.

**Comment by facundoolano** [comment]
did you monitor the memory usage? maybe you need to increase the node memory limit with --max-old-space-size

**Comment by facundoolano** [comment]
Closing for unactivity, reopen if issues persist.
